name: felloapp
description: Game-based Investments

publish_to: "none"

version: 4.2.1+175

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  animations: ^2.0.2
  another_flushbar: 1.12.29
  app_install_date: ^0.1.1
  appsflyer_sdk: ^6.5.2
  apxor_flutter:
    git:
      url: https://github.com/apxor/apxor-flutter-sdk.git
      ref: 19d6f70
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.2.0
  collection: ^1.15.0-nullsafety.4
  connectivity_plus: ^3.0.2
  dart_jsonwebtoken: ^2.4.2
  device_info_plus: 7.0.0
  device_preview: ^1.1.0
  encrypt: ^5.0.0
  external_app_launcher: ^3.1.0
  firebase_analytics: ^10.0.7
  firebase_auth: ^4.2.1
  firebase_core: ^2.4.0
  firebase_crashlytics: ^3.0.7
  firebase_database: ^10.0.7
  firebase_dynamic_links: ^5.0.9
  firebase_in_app_messaging: ^0.7.0-8
  firebase_messaging: ^14.1.4
  firebase_performance: ^0.9.0-7
  firebase_remote_config: ^3.0.7
  firebase_storage: ^11.0.8
  flutter:
    sdk: flutter
  flutter_facebook_sdk:
    path: packages/flutter_facebook_sdk/
  flutter_html: null
  flutter_inset_box_shadow: ^1.0.8
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.0
  flutter_spinkit: ^5.0.0
  flutter_svg: ^1.0.3
  flutter_windowmanager: ^0.2.0
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  google_sign_in: ^5.0.7
  http: ^0.13.3
  image_picker: ^0.8.3
  in_app_review: ^2.0.3
  intl: ^0.17.0
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  local_auth: ^2.1.2
  logger: ^1.0.0
  lottie: ^1.1.0
  mixpanel_flutter: ^2.0.0
  open_filex: ^4.3.1
  package_info_plus: ^3.0.2
  page_view_indicators: ^2.0.0
  path_provider: ^2.0.2
  paytm_allinonesdk: ^1.1.4
  pdf: ^3.1.0
  permission_handler: ^10.1.0
  property_change_notifier: ^0.3.0
  provider: ^6.0.2
  razorpay_flutter: ^1.3.0
  rxdart: ^0.27.7
  scratcher: ^2.3.0
  share_plus: ^6.3.0
  
  shared_preferences: ^2.0.6
  shared_preferences_android: ^2.0.13
  shared_preferences_ios: ^2.1.1
  shimmer: ^2.0.0
  showcaseview:
    path: packages/flutter_showcaseview
  sms_autofill: ^2.0.0
  story_view:
    git:
      url: https://github.com/KumarArab/story_view
      ref: 0c9c113
  syncfusion_flutter_gauges:
    path: packages/syncfusion_flutter_gauges
  truecaller_sdk: ^0.1.1
  upi_pay:
    path: packages/upi/
  url_launcher: ^6.1.8
  video_player: ^2.5.1
  webengage_flutter: ^1.2.1
  webview_flutter: ^3.0.4

dev_dependencies:
  build_runner: any
  flutter_test:
    sdk: flutter
  isar_generator: null
  

# dependency_overrides:
#    firebase_core_platform_interface: 4.5.1
flutter:
  uses-material-design: true

  assets:
    - images/
    - images/Tambola/
    - resources/augmont/fello-augmont-invoice.html
    - resources/fello-email-verification.html
    - resources/public.key
    - assets/images/
    - assets/images/icons/
    - assets/svg/
    - assets/vectors/
    - assets/vectors/icons/
    - assets/vectors/userAvatars/
    - assets/lotties/
    - assets/lotties/nav/

flutter_intl:
  main_locale: en_US
  enabled: true
  arb_dir: lib/util/localization/l10n
  output_dir: lib/util/localization/generated
