name: felloapp
description: Saving made fun

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  firebase_core: ^0.4.0+9
  firebase_auth: ^0.15.4
  cloud_firestore: ^0.13.0+1
  firebase_messaging: ^5.0.2
  firebase_storage: ^3.0.8
  provider: ^3.1.0
  get_it: ^1.0.3+2
  pin_input_text_field: ^2.0.3
  path_provider:
  morpheus: ^1.0.2
  flutter_spinkit: ^4.0.0
  cached_network_image: ^2.0.0
  http: ^0.12.0+3
  connectivity: ^0.4.6+2
  flushbar: ^1.10.4
  bottom_navy_bar: ^5.5.0

  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - images/logo_full_size.png
