name: felloapp
description: Game-based Investments

publish_to: "none"

version: 3.3.3+126

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.0
  cloud_firestore: ^3.1.6
  connectivity_plus: ^2.2.0
  device_info_plus: ^3.2.2
  device_unlock: ^1.1.2
  # device_preview: 1.0.0
  encrypt: ^5.0.0
  firebase_analytics: ^9.0.5
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  firebase_crashlytics: ^2.1.1
  firebase_database: ^9.0.5
  firebase_dynamic_links: ^2.0.7
  firebase_in_app_messaging: ^0.6.0+6
  firebase_messaging: ^11.2.5
  firebase_performance: ^0.8.0+4
  firebase_remote_config: ^1.0.4
  firebase_storage: ^10.0.2
  another_flushbar: 1.10.11
  flutter:
    sdk: flutter
  flutter_facebook_sdk: ^1.0.0
  flutter_localizations:
    sdk: flutter
  flutter_share_me: ^1.2.0
  flutter_spinkit: ^5.0.0
  flutter_svg: ^1.0.3
  get_it: ^7.2.0
  google_fonts: 2.1.0  
  google_sign_in: ^5.0.7
  http: ^0.13.3
  image_picker: ^0.8.3
  intl: ^0.17.0
  logger: ^1.0.0
  lottie: ^1.1.0
  webengage_flutter: ^1.0.3
  mixpanel_flutter: ^1.3.1
  open_filex: ^3.4.0
  package_info: ^2.0.0
  path_provider: ^2.0.2
  paytm_allinonesdk: ^1.1.4
  pdf: ^3.1.0
  permission_handler: ^8.1.4+2
  property_change_notifier: ^0.3.0
  provider: ^6.0.2
  share_plus: ^4.0.4
  shared_preferences: ^2.0.6
  sms_autofill: ^2.0.0
  url_launcher: ^6.0.9
  webview_flutter: ^3.0.0
  flutter_rating_bar: ^4.0.0
  in_app_review: ^2.0.3
  scratcher: 2.2.0
  truecaller_sdk: ^0.1.1
  app_install_date: ^0.1.1
  appsflyer_sdk: ^6.5.2
  external_app_launcher: ^2.0.2
  shimmer: ^2.0.0
  animations: ^2.0.2
  flutter_inset_box_shadow: ^1.0.8
  shared_preferences_android: ^2.0.13
  shared_preferences_ios: ^2.1.1
  flutter_html: ^3.0.0-alpha.5
  page_view_indicators: ^2.0.0

  isar: ^2.4.0
  isar_flutter_libs: 2.4.0
  upi_pay:
    git: 
      url: https://github.com/fellofinance/upi_pay
      ref: 41fd13c
  razorpay_flutter: ^1.3.0
  dart_jsonwebtoken: ^2.4.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  isar_generator: 2.4.0
  build_runner: any

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/Tambola/
    - resources/augmont/fello-augmont-invoice.html
    - resources/fello-email-verification.html
    - resources/public.key
    - assets/images/
    - assets/images/icons/
    - assets/svg/
    - assets/vectors/
    - assets/vectors/icons/
    - assets/vectors/userAvatars/
    - assets/lotties/
    - assets/lotties/nav/


flutter_intl:
  main_locale: en_US
  enabled: true
  arb_dir: lib/util/localization/l10n
  output_dir: lib/util/localization/generated
