name: felloapp
description: Game-based Investments

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+7

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.1
  firebase_analytics: ^7.0.1
  cloud_firestore: ^0.16.0+1
  firebase_messaging: ^6.0.16
  firebase_dynamic_links: ^0.7.0+1
  firebase_remote_config: ^0.6.0
  firebase_in_app_messaging: ^0.3.0+1
  provider: ^3.1.0
  get_it: ^1.0.3+2
  pin_input_text_field: ^2.0.3
  path_provider:
  flutter_spinkit: ^4.0.0
  cached_network_image: ^2.0.0
  http: ^0.12.0+3
  connectivity: ^0.4.6+2
  flushbar: ^1.10.4
  bottom_navy_bar: ^5.5.0
  upi_pay: ^0.2.1
  flutter_share_me: ^0.9.2
  url_launcher: ^5.7.0
  showcaseview: ^0.1.6
  flutter_html: ^1.2.0
  fl_animated_linechart: ^1.1.4
  google_fonts: ^1.1.1
  confetti: ^0.5.4+1
  lottie: ^0.7.0+1
  signature: ^3.2.0
  image_picker: ^0.6.7+21
  modal_progress_hud: ^0.1.3
  shared_preferences: ^0.5.7
  geolocator: ^6.1.14
  webview_flutter: ^1.0.7
  slider_button: ^0.6.0
  scratcher: ^1.4.0
  video_player: ^1.0.1
  camera: ^0.7.0+2
  path: ^1.7.0

  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - images/logo_full_size.png
    - images/transfer.png
    - images/diagonal-strike.png
    - images/games-small.png
    - images/grow-small.png
    - images/safe-small.png
    - images/save-small.png
    - images/winners-small.png
    - images/prizes-small.png
    - images/fello_logo.png
    - images/icici.png
    - images/sebi.png
    - images/amfi.png
    - images/whatsapp.png
    - images/onboard_collage-small.png
    - images/PAN_card.png
    - images/PAN_card_no_focussed.png
    - images/kyc_unavailable.png
    - images/checkmark.json
    - images/verification.json
    - images/scratch-card.png
    - images/Aadhar_card.jpg
    - images/Cancelled_cheque.png
    - resources/fello_tnc.html
    - resources/referral_policy.html
