name: felloapp
description: Game-based Investments

publish_to: "none"

version: 3.0.1+36

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cached_network_image: ^3.1.0
  camera: ^0.8.1+7
  cloud_firestore: ^2.4.0
  confetti: ^0.5.4+1
  connectivity_plus: ^1.1.0
  cupertino_icons: ^1.0.0
  device_info: ^2.0.2
  device_preview: ^0.7.4
  device_unlock: ^1.1.0
  encrypt: ^5.0.0
  firebase_analytics: ^8.2.0
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  firebase_crashlytics: ^2.1.1
  firebase_database: ^7.1.2
  firebase_dynamic_links: ^2.0.7
  firebase_in_app_messaging: ^0.5.0+7
  firebase_messaging: ^10.0.4
  firebase_performance: ^0.7.1+1
  firebase_remote_config: ^0.10.0+3
  firebase_storage: ^10.0.2
  fl_chart: ^0.36.3
  flushbar: ^1.10.4
  flutter:
    sdk: flutter
  flutter_facebook_sdk: ^1.0.0
  flutter_html: ^2.1.1
  flutter_html_to_pdf: ^0.6.1
  flutter_image_compress: ^1.1.0
  flutter_localizations:
    sdk: flutter
  flutter_share_me: ^0.11.1
  flutter_spinkit: ^5.0.0
  flutter_staggered_grid_view: ^0.4.0
  flutter_svg: ^0.22.0
  freshchat_sdk: ^0.8.0
  get_it: ^7.2.0
  google_fonts: ^2.1.0
  google_sign_in: ^5.0.7
  http: ^0.13.3
  image_gallery_saver: ^1.6.9
  image_picker: ^0.8.3
  in_app_update: ^2.0.0
  intl: ^0.17.0
  logger: ^1.0.0
  lottie: ^1.1.0
  mixpanel_flutter: ^1.3.1
  open_file: ^3.2.1
  package_info: ^2.0.0
  path: ^1.8.0
  path_provider: ^2.0.2
  pdf: ^3.1.0
  permission_handler: ^8.1.4+2
  property_change_notifier: ^0.3.0
  provider: ^5.0.0
  razorpay_flutter: ^1.2.7
  rive: ^0.7.22
  share_plus: ^2.1.4
  shared_preferences: ^2.0.6
  shimmer_animation: ^2.1.0+1
  slider_button: ^0.6.0
  sms_autofill: ^2.0.0
  synchronized: ^3.0.0
  url_launcher: ^6.0.9
  video_player: ^2.1.12
  webview_flutter: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/Tambola/
    - images/GamePoll/
    - images/svgs/
    - images/lottie/
    - images/process/
    - images/zerobal/
    - resources/augmont/fello-augmont-invoice.html
    - resources/fello-email-verification.html

    - assets/images/
    - assets/images/icons/
    - assets/vectors/
    - assets/vectors/icons/
    - assets/vectors/drawer/
    - assets/lotties/

  fonts:
    - family: Cucciolo
      fonts:
        - asset: fonts/Cucciolo Rough.ttf
    - family: Arctick
      fonts:
        - asset: fonts/arctick/arctik-2.ttf
        - asset: fonts/arctick/arctik-3.5.ttf
          weight: 500
        - asset: fonts/arctick/arctik-5.ttf
          weight: 700

flutter_intl:
  main_locale: en_US
  enabled: true
  arb_dir: lib/util/localization/l10n
  output_dir: lib/util/localization/generated
