name: felloapp
description: Game-based Investments

publish_to: "none"

version: 6.1.3+285

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  animations: ^2.0.2
  another_flushbar: ^1.12.30
  app_set_id: ^1.0.0
  app_install_date: ^0.1.1
  appsflyer_sdk: ^6.5.2
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.2.0
  collection: ^1.15.0-nullsafety.4
  connectivity_plus: ^5.0.2
  dart_jsonwebtoken: ^2.4.2
  device_info_plus: ^9.0.0
  device_preview: ^1.1.0
  encrypt: ^5.0.0
  firebase_analytics: ^10.7.1
  firebase_auth: ^4.16.0
  firebase_core: ^2.25.1
  firebase_crashlytics: ^3.4.5
  firebase_database: ^10.3.5
  firebase_dynamic_links: ^5.0.9
  firebase_in_app_messaging: ^0.7.4+5
  firebase_messaging: ^14.7.5
  firebase_performance: ^0.9.3+5
  firebase_remote_config: ^4.3.5
  firebase_storage: ^11.5.2
  flutter:
    sdk: flutter
  flutter_facebook_sdk:
    path: packages/flutter_facebook_sdk/
  flutter_inset_box_shadow: ^1.0.8
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.0
  flutter_spinkit: ^5.0.0
  flutter_svg: ^2.0.5
  flutter_windowmanager: ^0.2.0
  get_it: ^7.2.0
  google_fonts: ^6.1.0
  google_sign_in: ^5.0.7
  image_picker: ^1.0.8
  intl: ^0.19.0
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  local_auth: ^2.1.2
  logger: ^2.0.0
  lottie: ^2.3.2
  mixpanel_flutter: ^2.0.0
  open_filex: ^4.3.1
  package_info_plus: ^8.0.2
  page_view_indicators: ^2.0.0
  path_provider: ^2.0.2
  pdf: ^3.1.0
  permission_handler: ^11.0.0
  property_change_notifier: ^0.3.0
  provider: ^6.0.2
  razorpay_flutter: ^1.3.0
  scratcher: ^2.5.0
  singular_flutter_sdk: ^1.0.13
  share_plus: ^7.0.2
  shared_preferences: ^2.0.6
  shimmer: ^2.0.0
  sms_autofill: ^2.4.0
  syncfusion_flutter_gauges: ^24.1.46
  truecaller_sdk: ^0.1.2
  upi_pay:
    path: packages/upi/
  url_launcher: ^6.1.8
  video_player: ^2.9.1
  webview_flutter: ^4.2.0
  advertising_id: ^2.4.0
  flutter_hooks: ^0.18.6
  tuple: ^2.0.1
  android_play_install_referrer: ^0.2.1
  youtube_player_iframe: ^4.0.4
  flutter_bloc: ^8.1.3
  syncfusion_flutter_charts: ^24.1.46
  clevertap_plugin: ^1.8.1
  action_slider: ^0.7.0
  vibration: ^1.7.7
  flutter_vibrate: ^1.3.0
  in_app_update: ^4.1.0
  firebase_instance_id: ^1.0.0
  dio: ^5.3.3
  dio_http2_adapter: ^2.3.1+1
  json_annotation: ^4.8.1
  bloc: ^8.1.2
  equatable: ^2.0.5
  flutter_blurhash: ^0.8.2
  story_view: ^0.16.0
  freezed_annotation: ^2.4.1
  hmssdk_flutter: ^1.10.6
  sliver_tools: ^0.2.12
  super_tooltip: ^2.0.7
  focus_detector_v2: ^3.1.0+1
  flutter_widget_from_html_core: ^0.15.2
  dropdown_button2: ^2.3.9
  badges: ^3.1.2
  flutter_linkify: ^6.0.0
  dots_indicator: ^3.0.0
  draggable_widget: ^2.0.0
  pointer_interceptor: ^0.10.1+2
  inview_notifier_list: ^3.0.0
  design_system:
    path: _packages/design_system/
  flutter_isolate: ^2.0.2
  injectable_generator: ^1.4.1
  flutter_screenutil: ^5.9.0
  visibility_detector: ^0.4.0+2
  timeago: ^3.7.0
  keyboard_detection: ^0.7.3
  webengage_flutter: ^1.3.0
  vertical_scrollable_tabview: ^0.1.1
  scroll_to_index: ^3.0.1
  injectable: ^1.5.4
  flutter_branch_sdk: ^7.1.0
  volume_watcher: ^2.0.1



dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0
  flutter_lints: ^2.0.1
  integration_test:
    sdk: flutter
  husky: ^0.1.6
  # dart_code_metrics: 5.7.5
  json_serializable: ^6.7.1
  freezed: ^2.4.6


flutter:
  uses-material-design: true

  assets:
    - images/
    - images/Tambola/
    - resources/augmont/fello-augmont-invoice.html
    - resources/fello-email-verification.html
    - resources/public.key
    - assets/images/
    - assets/images/icons/
    - assets/svg/
    - assets/vectors/
    - assets/vectors/gif/
    - assets/vectors/psp/
    - assets/vectors/icons/
    - assets/vectors/userAvatars/
    - assets/lotties/
    - assets/lotties/nav/
    - assets/hms/
    - assets/hms/icons/
    - shorebird.yaml

flutter_intl:
  main_locale: en_US
  enabled: true
  arb_dir: lib/util/localization/l10n
  output_dir: lib/util/localization/generated
