name: felloapp
description: Game-based Investments

publish_to: 'none'

version: 2.4.0+17

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.1
  firebase_analytics: ^7.0.1
  cloud_firestore: ^0.16.0+1
  firebase_storage: ^7.0.0
  firebase_dynamic_links: ^0.7.0+1
  firebase_remote_config: ^0.6.0
  firebase_in_app_messaging: ^0.3.0+1
  firebase_messaging: ^8.0.0-dev.14
  firebase_database: ^6.0.0
  google_sign_in: ^4.5.9
  #core packages
  connectivity: ^0.4.6+2
  encrypt: ^4.1.0
  flutter_local_notifications: ^4.0.1+2
  flutter_html_to_pdf: ^0.6.0
  freshchat_sdk: ^0.6.0
  path: ^1.8.0
  path_provider: ^1.6.27
  permission_handler: ^5.1.0+2
  provider: ^5.0.0
  get_it: ^6.0.0
  geolocator: ^6.1.14
  http: ^0.12.0+3
  open_file: ^3.1.0 #for opening pdfs
  package_info: ^2.0.0
  razorpay_flutter: ^1.2.6
  shared_preferences: ^0.5.7
  share: ^0.6.5+4
  synchronized: ^3.0.0
  url_launcher: ^5.7.0
  device_unlock : ^1.1.2
  in_app_update: ^2.0.0
  #ui packages
  camera: ^0.7.0+2
  cached_network_image: ^2.0.0
  confetti: ^0.5.4+1
  flip_card: ^0.5.0
  flat_icons_flutter: ^1.0.2
  flutter_spinkit: ^4.0.0
  flutter_share_me: ^0.9.2
  flutter_html: ^1.2.0
  flutter_image_compress: ^0.7.0
  flutter_staggered_grid_view: ^0.4.0
  flutter_svg: ^0.19.3
  flushbar: ^1.10.4
  fl_animated_linechart: ^1.1.4
  google_fonts: ^1.1.1
  image_picker: ^0.6.7+21
  lottie: ^0.7.0+1
  modal_progress_hud: ^0.1.3
  pie_chart: ^4.0.1
  screenshot: ^1.2.1
  scratcher: ^1.4.0
  showcaseview: ^0.1.6
  signature: ^3.2.0
  slider_button: ^0.6.0
  sms_autofill: ^2.0.0
  video_player: ^1.0.1
  webview_flutter: ^1.0.7

  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - images/
    - images/Tambola/
    - images/GamePoll/
    - images/svgs/
    - images/lottie/
    - images/process/
    - resources/augmont/fello-augmont-invoice.html
    - resources/fello-email-verification.html


