name: felloapp
description: Game-based Investments

publish_to: "none"

version: 6.6.4+318

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  animations: ^2.0.2
  another_flushbar: ^1.12.30
  app_install_date: ^0.1.1
  app_set_id: ^1.0.0
  cached_network_image: ^3.2.3
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.5.0
  collection: ^1.18.0 
  connectivity_plus: ^6.1.0
  device_info_plus: ^9.0.0
  encrypt: ^5.0.0
  firebase_analytics: ^11.3.5
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  firebase_crashlytics: ^4.1.5
  firebase_in_app_messaging: ^0.8.0+10
  firebase_instance_id: ^1.1.0
  firebase_messaging: ^15.1.5
  firebase_performance: ^0.10.0+10
  firebase_storage: ^12.3.6
  flutter:
    sdk: flutter
  flutter_meta_sdk: ^1.0.5
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.10+1
  flutter_windowmanager: ^0.2.0
  get_it: ^7.2.0
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.6
  image_picker: ^1.0.8
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  local_auth: ^2.1.2
  logger: ^2.4.0
  lottie: ^3.1.2
  mixpanel_flutter: ^2.3.1
  package_info_plus: ^8.0.2
  path_provider: ^2.0.2
  pdf: ^3.1.0
  permission_handler: ^11.0.0
  property_change_notifier: ^0.3.0
  provider: ^6.0.2
  razorpay_flutter: ^1.3.0
  scratcher: ^2.5.0
  share_plus: ^7.0.2
  shared_preferences: ^2.0.6
  shimmer: ^3.0.0
  sms_autofill: ^2.4.0
  syncfusion_flutter_gauges: ^27.1.58
  upi_pay:
    path: packages/upi/
  url_launcher: ^6.1.8
  video_player: ^2.9.1
  webview_flutter: ^4.2.0
  advertising_id: ^2.4.0
  flutter_hooks: ^0.20.5
  tuple: ^2.0.2
  android_play_install_referrer: ^0.4.0
  youtube_player_iframe: ^4.0.4
  flutter_bloc: ^9.1.0
  syncfusion_flutter_charts: ^27.1.58
  vibration: ^1.7.7
  in_app_update: ^4.1.0
  dio: ^5.3.3
  dio_http2_adapter: ^2.3.1+1
  json_annotation: ^4.8.1
  equatable: ^2.0.7
  flutter_blurhash: ^0.8.2
  story_view: ^0.16.5
  freezed_annotation: ^2.4.1
  hmssdk_flutter: ^1.10.6
  super_tooltip: ^2.0.8
  focus_detector_v2: ^3.1.0+1
  flutter_widget_from_html_core: ^0.15.2
  dropdown_button2: ^2.3.9
  badges: ^3.1.2
  flutter_linkify: ^6.0.0
  dots_indicator: ^3.0.0
  draggable_widget: ^2.0.0
  pointer_interceptor: ^0.10.1+2
  design_system:
    path: _packages/design_system/
  flutter_screenutil: ^5.9.3
  timeago: ^3.7.0
  keyboard_detection: ^0.7.3
  webengage_flutter: ^1.4.2
  rect_getter: ^1.1.0
  injectable: ^1.5.4
  flutter_branch_sdk: ^7.1.0
  smooth_page_indicator: ^1.2.0+3
  bordered_text: ^2.0.0
  transparent_image: ^2.0.1
  hydrated_bloc: ^10.0.0
  socket_io_client: ^3.0.2
  flutter_local_notifications: ^18.0.1
  app_links: ^6.3.2

dev_dependencies:
  build_runner: any
  build_runner_core: ^7.3.2
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  husky: ^0.1.6
  integration_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  json_serializable: ^6.8.0
  

flutter:
  uses-material-design: true

  assets:
    - images/
    - resources/augmont/fello-augmont-invoice.html
    - resources/fello-email-verification.html
    - resources/public.key
    - assets/images/
    - assets/images/icons/
    - assets/svg/
    - assets/vectors/
    - assets/vectors/gif/
    - assets/vectors/psp/
    - assets/vectors/icons/
    - assets/vectors/userAvatars/
    - assets/lotties/
    - assets/hms/
    - assets/hms/icons/

flutter_intl:
  main_locale: en_US
  enabled: true
  arb_dir: lib/util/localization/l10n
  output_dir: lib/util/localization/generated
