name: felloapp
description: Game-based Investments

publish_to: 'none'

version: 2.5.5+28

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cloud_firestore: ^2.4.0
  firebase_analytics: ^8.2.0
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  firebase_crashlytics : ^2.1.1
  firebase_database: ^7.1.2
  firebase_dynamic_links: ^2.0.7
  firebase_in_app_messaging: ^0.5.0+7
  firebase_messaging: ^10.0.4
  firebase_remote_config: ^0.10.0+3
  firebase_storage: ^10.0.2
  google_sign_in: ^5.0.7

  #core packages
  connectivity_plus: ^1.1.0
#  flutter_local_notifications: ^8.0.0
  encrypt: ^5.0.0
  flutter_html_to_pdf: ^0.6.1
  freshchat_sdk: ^0.8.0
  get_it: ^7.2.0
  http: ^0.13.3
  open_file: ^3.2.1
  intl: ^0.17.0
  path: ^1.8.0
  permission_handler: ^8.1.4+2
  path_provider: ^2.0.2
  package_info: ^2.0.0
  provider: ^5.0.0
  razorpay_flutter: ^1.2.6
  shared_preferences: ^2.0.6
  share_plus: ^2.1.4
  synchronized: ^3.0.0
  url_launcher: ^6.0.9
  in_app_update: ^2.0.0
  device_info : ^2.0.2
  image_gallery_saver: ^1.6.9
  pdf: ^3.1.0
  flutter_facebook_sdk: ^1.0.0
  webview_flutter: ^2.0.13
  #ui packages
  camera: ^0.8.1+7
  cached_network_image: ^3.1.0
  confetti: ^0.5.4+1
  device_unlock: ^1.1.0
  flutter_spinkit: ^5.0.0
  flutter_share_me: ^0.11.1
  flutter_html: ^2.1.1
  flutter_image_compress: ^1.1.0
  flutter_staggered_grid_view: ^0.4.0
  flutter_svg: ^0.22.0
  flushbar: ^1.10.4
  fl_chart: ^0.36.3
  google_fonts: ^2.1.0
  image_picker: ^0.8.3
  lottie: ^1.1.0
  rive: ^0.7.22
  shimmer_animation : ^2.1.0+1
  slider_button: ^0.6.0
  sms_autofill: ^2.0.0
  video_player: ^2.1.12
  flutter_localizations:
    sdk: flutter

  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  logger: ^1.0.0


flutter:
  uses-material-design: true

  assets:
    - images/
    - images/Tambola/
    - images/GamePoll/
    - images/svgs/
    - images/lottie/
    - images/process/
    - images/zerobal/
    - resources/augmont/fello-augmont-invoice.html
    - resources/fello-email-verification.html


  fonts:
    - family: Cucciolo
      fonts:
        - asset: fonts/Cucciolo Rough.ttf
flutter_intl:
  main_locale: en_US
  enabled: true
