name: stac
description: Stac is a Server-Driven UI (SDUI) framework for Flutter. Stac allows you to build beautiful cross-platform applications with JSON in real time.
version: 0.10.0
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

topics:
  - ui
  - widget
  - server-driven-ui
  - dynamic-widgets

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  logger: ^2.5.0
  dio: ^5.7.0
  stac_framework:
    path: ../stac_framework

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.4.8
  freezed: ^2.4.6
  json_serializable: ^6.7.1
