name: stac_framework
description: The Stac Framework enables easy creation of parsers for widgets and actions, enhancing Stac's functionality and supporting custom implementations.
version: 0.2.2
publish_to: "none"

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=1.17.0"

topics:
  - ui
  - widget
  - server-driven-ui
  - dynamic-widgets

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
