name: flutter_preload_videos
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  video_player: ^2.6.1
  flutter_isolate: ^2.0.2
  injectable: ^1.4.1
  injectable_generator: ^1.4.1
  flutter_svg: ^2.0.5
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: any
  freezed: any
  
flutter:
  assets:
    - lib/src/assets/
    - lib/src/assets/svg/
